#!/usr/bin/env python3
"""
PyTorch Lightning DataModule for the multimodal MER pipeline.

This module wraps:
- `MultimodalManifestDataset`
- `build_dataloader` / `build_split_dataloaders`

to provide a clean Lightning-compatible interface.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Literal, Optional, Sequence

from torch.utils.data import DataLoader

try:
    from lightning.pytorch import LightningDataModule
except Exception:
    try:
        from pytorch_lightning import LightningDataModule  # type: ignore[no-redef]
    except Exception:
        LightningDataModule = object  # type: ignore[assignment,misc]

try:
    from .data_loader import (
        BatchDict,
        CollateConfig,
        DataLoaderConfig,
        build_split_dataloaders,
        build_split_dataloaders_pkl,
    )
    from .dataset import AudioExtractorConfig, TARGET_COLUMNS, VideoExtractorConfig
except ImportError:
    from data_loader import (  # type: ignore[no-redef]
        BatchDict,
        CollateConfig,
        DataLoaderConfig,
        build_split_dataloaders,
        build_split_dataloaders_pkl,
    )
    from dataset import AudioExtractorConfig, TARGET_COLUMNS, VideoExtractorConfig  # type: ignore[no-redef]


SplitName = Literal["train", "val", "test"]


class MERDataModule(LightningDataModule):
    """
    Minimal Lightning DataModule for manifest-based multimodal MER training.

    Parameters
    ----------
    manifest_path:
        Path to the manifest generated by `build_manifest.py`.
    audio_cfg:
        Audio foundation-model extractor configuration.
    video_cfg:
        Video foundation-model extractor configuration.
    train_loader_cfg:
        DataLoader options for the training split.
    eval_loader_cfg:
        DataLoader options for validation/test; if None, derived from train config
        with `shuffle=False`.
    collate_cfg:
        Optional collation/padding configuration.
    target_columns:
        Target label columns in manifest order; defaults to six MER intensities.
    strict_path_check:
        Whether dataset should enforce file existence checks.
    """

    def __init__(
        self,
        manifest_path: Path,
        audio_cfg: AudioExtractorConfig,
        video_cfg: VideoExtractorConfig,
        train_loader_cfg: DataLoaderConfig,
        eval_loader_cfg: Optional[DataLoaderConfig] = None,
        collate_cfg: Optional[CollateConfig] = None,
        target_columns: Sequence[str] = TARGET_COLUMNS,
        strict_path_check: bool = True,
    ) -> None:
        super().__init__()
        self.manifest_path = Path(manifest_path)
        self.audio_cfg = audio_cfg
        self.video_cfg = video_cfg
        self.train_loader_cfg = train_loader_cfg
        self.eval_loader_cfg = eval_loader_cfg
        self.collate_cfg = collate_cfg
        self.target_columns = list(target_columns)
        self.strict_path_check = strict_path_check

        self._dataloaders: Optional[Dict[SplitName, DataLoader[BatchDict]]] = None

    def setup(self, stage: Optional[str] = None) -> None:
        """
        Build split dataloaders once and reuse across trainer stages.

        Lightning stages:
        - "fit": train + val
        - "validate": val
        - "test": test
        - "predict": not used here
        """
        if self._dataloaders is not None:
            return

        self._dataloaders = build_split_dataloaders(
            manifest_path=self.manifest_path,
            audio_cfg=self.audio_cfg,
            video_cfg=self.video_cfg,
            train_loader_cfg=self.train_loader_cfg,
            eval_loader_cfg=self.eval_loader_cfg,
            collate_cfg=self.collate_cfg,
            target_columns=self.target_columns,
            strict_path_check=self.strict_path_check,
        )

    def train_dataloader(self) -> DataLoader[BatchDict]:
        if self._dataloaders is None:
            self.setup(stage="fit")
        assert self._dataloaders is not None
        return self._dataloaders["train"]

    def val_dataloader(self) -> DataLoader[BatchDict]:
        if self._dataloaders is None:
            self.setup(stage="fit")
        assert self._dataloaders is not None
        return self._dataloaders["val"]

    def test_dataloader(self) -> DataLoader[BatchDict]:
        if self._dataloaders is None:
            self.setup(stage="test")
        assert self._dataloaders is not None
        return self._dataloaders["test"]


class MERDataModulePkl(LightningDataModule):
    """DataModule for Zenodo processed_mosei.pkl (no manifest, no raw audio/video files)."""

    def __init__(
        self,
        pkl_path: Path,
        train_loader_cfg: DataLoaderConfig,
        eval_loader_cfg: Optional[DataLoaderConfig] = None,
        collate_cfg: Optional[CollateConfig] = None,
        train_ratio: float = 0.7,
        val_ratio: float = 0.15,
        seed: int = 561,
    ) -> None:
        super().__init__()
        self.pkl_path = Path(pkl_path)
        self.train_loader_cfg = train_loader_cfg
        self.eval_loader_cfg = eval_loader_cfg
        self.collate_cfg = collate_cfg
        self.train_ratio = train_ratio
        self.val_ratio = val_ratio
        self.seed = seed
        self._dataloaders: Optional[Dict[SplitName, DataLoader[BatchDict]]] = None

    def setup(self, stage: Optional[str] = None) -> None:
        if self._dataloaders is not None:
            return
        self._dataloaders = build_split_dataloaders_pkl(
            pkl_path=self.pkl_path,
            train_loader_cfg=self.train_loader_cfg,
            eval_loader_cfg=self.eval_loader_cfg,
            collate_cfg=self.collate_cfg,
            train_ratio=self.train_ratio,
            val_ratio=self.val_ratio,
            seed=self.seed,
        )

    def train_dataloader(self) -> DataLoader[BatchDict]:
        if self._dataloaders is None:
            self.setup(stage="fit")
        assert self._dataloaders is not None
        return self._dataloaders["train"]

    def val_dataloader(self) -> DataLoader[BatchDict]:
        if self._dataloaders is None:
            self.setup(stage="fit")
        assert self._dataloaders is not None
        return self._dataloaders["val"]

    def test_dataloader(self) -> DataLoader[BatchDict]:
        if self._dataloaders is None:
            self.setup(stage="test")
        assert self._dataloaders is not None
        return self._dataloaders["test"]
